version: '2'
services:
    torgcrm-app:
        image: torgcrm
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://torgcrm-postgresql:5432/TorgCRM
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    torgcrm-postgresql:
        extends:
            file: postgresql.yml
            service: torgcrm-postgresql
